service: serverless-bolt-js
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
      - http:
          path: /slack/install
          method: get
      - http:
          path: /slack/user_install
          method: get
      - http:
          path: /slack/oauth_redirect
          method: get
useDotenv: true
plugins:
  - serverless-offline
